server:
  port: 9096
spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://wahid:Ep7ca266p7xfxKAp@hungersaviour.dda5hqg.mongodb.net/?retryWrites=true&w=majority
      database: orders
#      uuid-representation: STANDARD
  kafka:
    consumer:
      bootstrap-servers:
        - "localhost:19092"
        - "localhost:29092"
        - "localhost:39092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}