server:
  port: 9090
spring:
  application:
    name: restaurant-service
  datasource:
    url: jdbc:mysql://localhost:3306/restaurants?createDatabaseIfNotExist=true
    username: root
    password: wahidur
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    baseline-on-migrate: true

eureka:
  client:
    register-with-eureka: ${REGISTER_WITH_EUREKA:true}
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}